version: 0.2

env:
  variables:
    FLASK_APP: app.py
    FLASK_ENV: development

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pytest
      - export FLASK_APP=app.py
      - export FLASK_ENV=development

  pre_build:
    commands:
      - echo Pre-build phase complete
      - export PYTHONPATH=$PYTHONPATH:$(pwd)/algorithms  # Add the algorithms directory to the PYTHONPATH

  build:
    commands:
      - echo Running tests...
      - pytest  # or `flask run` if you want to start the Flask app for testing purposes

  post_build:
    commands:
      - echo Build complete!
      - echo You can deploy the app now or test further if needed.

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/root/.cache/pip/**/*'
    - '/home/codebuild/.cache/pip/**/*'  # Add this line if caching also applies to this path
